name: CI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests with coverage
        run: npm run coverage

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: ignore

      - name: Summarize coverage
        if: always()
        run: |
          if [ -f coverage/lcov-report/index.html ]; then
            echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
            grep -m1 -E "All files" coverage/coverage-final.json >/dev/null 2>&1 || true
            # Print text summary if available
            if [ -f coverage/coverage-final.json ]; then
              echo '\n(See artifact for full HTML report)' >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "No coverage report generated" >> $GITHUB_STEP_SUMMARY
          fi
